### ISSUE TITLE
Skip redrawing RPROMPT when invoking geometry::info?

### ISSUE THREAD

**Issue by jedahan** [jedahan/geometry#12]
Right now, when you press enter (for `geometry::info`) we redraw the entire prompt, like so:

<img width="823" alt="screen shot 2019-02-17 at 6 23 29 pm" src="https://user-images.githubusercontent.com/32407/52921072-26b5f480-32e1-11e9-89d3-193670ea28d2.png">

It looks cleaner to me, to skip drawing RPROMPT if we are doing the magic enter geometry::info, which would look like this:

<img width="828" alt="screen shot 2019-02-17 at 6 22 23 pm" src="https://user-images.githubusercontent.com/32407/52921051-02f2ae80-32e1-11e9-9efb-1d6c5d71979a.png">

Open to discussion or simple thumbs up thumbs down

**Comment by jedahan** [comment]
looking forward to any input from @MarioRicalde or any of our other users

**Comment by MarioRicalde** [comment]
Although I do agree that it looks cleaner, I hesitate to say yes to this mainly because this change would create another issue, which I find it more frustrating than small delays: Inconsistency.

At this point we reach a fork, where we have to pick what's the lesser evil of both things:

How long does it take to load the `RPROMPT`? My understanding is that because it's async it shouldn't, in theory, cause any lag in the actual usability, correct me if I'm wrong.

**Comment by jedahan** [comment]
Its not long, and I guess I can see a use case where maybe you move directories instead of simply display information in GEOMETRY_INFO, so I will close this for now and maybe later re-open when this branch gets merged upstream.
